### ISSUE TITLE
Build failure on Windows

### ISSUE THREAD

**Issue by tyru** [amakan/amakankan#10]
README.md に書いてある以下のコマンドを実行すると現状 (HEAD= a56e9edeb6269ea181c4879e0ef279afef1572e2) エラーが出ます。

> 1度だけビルドを行うには、以下のスクリプトを実行してください。
> 
> docker-compose run --rm node yarn run build

エラーメッセージは以下の通りです。

```
C:\msys64\home\tyru\git\amakankan>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

C:\msys64\home\tyru\git\amakankan>docker-compose run --rm node yarn run build
yarn run v0.18.1
$ run-s build:common build:extensions
sh: 1: run-s: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

試しに `... yarn run build:common:javascripts` してみると今度は `webpack` が無いと言われました。

```
C:\msys64\home\tyru\git\amakankan>docker-compose run --rm node yarn run build:common:javascripts
yarn run v0.18.1
$ NODE_ENV=production webpack
sh: 1: webpack: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

MSYS 上で webpack コマンドを find コマンドで探してみたところ、ちゃんとありました。

```
[MSYS] $ find node_modules -type f -iname 'webpack'
node_modules/.bin/webpack
```

**Comment by r7kamura** [comment]
@tyru Node.js を動かすための Docker イメージの中に、適切に npm パッケージがインストールされていないのかもしれません。

以下のスクリプトで、Node.js 用のイメージを再生成できます。普通は、package.json を更新したときなどに、このスクリプトを利用することになります。

```bash
docker-compose build node
```

このスクリプトでは、ホスト側（今回であれば Windows 側）から package.json と yarn.lock をコンテナ側（Node.js 側を動かす Docker コンテナ側）にコピーした後、このファイルがカレントディレクトリに存在している状態で `yarn install` が実行されるようになっています。

普通はこのスクリプトによって `webpack` もインストールされるはずですが、何らかの理由でホスト側から適切にファイルがコピーされないなど、Windows 特有の事情で問題が起きているのかもしれません。

一度上記のスクリプトを実行してみてもらえますか？

---

ちなみに、Node.js のイメージの中に適切に node_modules がインストールされているかどうかを調べるには、例えば以下のようなスクリプトが利用できます。

```bash
docker-compose run --rm node ls -la node_modules
```

このスクリプトは、Node.js 用のイメージの中で、`/app` をカレントディレクトリとして、`ls -la node_modules` を実行します。正常に webpack がインストールされていれば、この出力の中に webpack のディレクトリ名が含まれます。

**Comment by tyru** [comment]
`docker-compose build node` してませんでした…！
`node_modules` がインストールされてるかも合わせて確認してみます！

**Comment by tyru** [comment]
`docker-compose build node` を実行したら無事ビルドできました！
ありがとうございました！

**Comment by r7kamura** [comment]
おお、良かったです 👍 
また何か困ったら Issue 立てるか Twitter で聞くかやりやすい方で尋ねてください 🙏

**Comment by tyru** [comment]
ちなみにこれって必須だったりしますか？
もしそうなら docker-compose build node を README.md に書いておいてもらえると参加する人が助かるかと思います…！
もし面倒であれば、文面合ってるか自信ないですが、自分の方で PR 送っても構いませんがどうしましょう？

**Comment by r7kamura** [comment]
> ちなみにこれって必須だったりしますか？

通常は、初めて実行する場合に自動的にイメージがビルドされるので、必須ではありません。

**Comment by tyru** [comment]
ふむ…なるほど。
なぜ実行されなかったかは分かりませんが了解です。
（おそらく Windows 特有の問題か手順ミス…？）
