### ISSUE TITLE
Notification will never appear after timeout

### ISSUE THREAD

**Issue by tyru** [amakan/amakankan#11]
#8 では revert しましたが、一度タイムアウトやユーザーのクリックにより通知のバルーン (?) が消えた後に background.js に通知が来ると、`notificationId` がすでに消えたバルーンを指しているため、以後バルーンが表示されません。
以下はそれを修正するコミットです（リネームなどにより cherry-pick はできない状態になっているはずですが、参考までに）。

https://github.com/amakan/amakankan/commit/ea015779b248120c66ef9102846f92aef7c96713

**Comment by tyru** [comment]
PR 送りなおそうかと思いましたが、 #10 のエラーが出てよく分からなくて issue 化してしまった次第です…（すみません docker-compose 勉強します…）
ちなみにベルアラートに限って言えば 74725dec9c149c4feeadac8d1295b0d4cc22a602 でタイムアウトは起きないぐらいには高速化したので、再現させるとしたら×ボタンをクリックしてわざと消すぐらいでしょうか。

**Comment by r7kamura** [comment]
ありがとうございます 🙏

**Comment by r7kamura** [comment]
https://github.com/amakan/amakankan/pull/12 で対応しようと思います
