### ISSUE TITLE
[Bell alert] Do not send unreleased books

### ISSUE THREAD

**Issue by tyru** [amakan/amakankan#13]
# Twitter 上での会話

> @_tyru_ サーバ側で弾くことも出来るんですが、リクエストを受けるのも無駄なので、現在日時より先のやつはインポートしないようにとか出来ますか？
> https://twitter.com/r7kamura/status/826629564793188352

----

> 度々すみません。さっきのインポートしないようにするのって、ベルアラートのみ対応する事もできますが、background.js の sendProductDataToAmakan() で readAt 見て送らないようにするのもできますがどっちがいいですか？
> https://twitter.com/_tyru_/status/826647829355520000

@r7kamura 上記への返答ってどのようになりますでしょうか？

**Comment by r7kamura** [comment]
@tyru おっ、すみません 2/1 以降の mention 見逃してました 🙇 

確かに background.js の方でチェックすれば、全てのサービスで対応することが保証されるので良さそうですね。background.js 側で対応する方針にしましょう。

**Comment by tyru** [comment]
了解です！

**Comment by tyru** [comment]
う…既存コードでは `readAt` は文字列（`YYYY-MM-DD 00:00:00`）として渡ってくるんでした…
一旦パースしてもいいですが、できれば各サービスのコードからは `Date` 型で渡すよう変更したい…

**Comment by tyru** [comment]
> う…既存コードでは readAt は文字列（YYYY-MM-DD 00:00:00）として渡ってくるんでした…
> 一旦パースしてもいいですが、できれば各サービスのコードからは Date 型で渡すよう変更したい…

やっぱり既存コードを変更するのは怖いので、background.js で `readAt` が未来日時かどうかの判定をかなり防御的なコードで書いてるところです（そしてなぜか通知が出なかったりで苦戦してます…）。
